language: ruby

rvm:
- 2.1.1

script:
- jekyll build
#- htmlproof ./_site # thorough check on links, but reports an excess of false errors currently so turning off

# branch whitelist
branches:
  only:
  - gh-pages     # test only the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
