language: c
branches:
  only:
  - draft
env:
  global:
  - default_branch_scenario="published/subcountry2014"
  - study_area="China"
  - secure: M5igum6cJ1w14Qc/fr8W3H+wZOHQYAMJpdtr9DJIKL6t1fypTEv/VMbAdRdOlU22aGPfsAmhoveeWiAaOPR/qdM22DshsWhWBk7eNl9sKAStrJpHWJdoOgud0KoP8PSf++SvEmmCiX2D/cB/55SM+7E6VJ5f1jOeKCHjxMdarKY=
matrix:
  fast_finish: true
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- curl -OL http://raw.github.com/OHI-Science/ohi-webapps/master/ohi-travis-functions.R
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap
- sudo apt-get install pandoc
install:
- ./travis-tool.sh install_r zoo
- ./travis-tool.sh install_r psych
- ./travis-tool.sh install_r tidyr
- ./travis-tool.sh install_r brew
- ./travis-tool.sh install_r rmarkdown
- ./travis-tool.sh install_r httr
- ./travis-tool.sh install_github ropensci/git2r
- ./travis-tool.sh install_github ohi-science/rCharts
- ./travis-tool.sh install_github ohi-science/ohicore@dev
- git config --global user.email "bbest@nceas.ucsb.edu"
- git config --global user.name "Ben Best"
script:
- Rscript ohi-travis-functions.R calculate_scores && Rscript ohi-travis-functions.R
  create_results && Rscript ohi-travis-functions.R push_branch draft && Rscript ohi-travis-functions.R
  push_branch published && Rscript ohi-travis-functions.R create_pages
after_failure:
- ./travis-tool.sh dump_logs
notifications:
  email:
    recipients:
    - bbest@nceas.ucsb.edu
    on_success: change
    on_failure: always
