# configuration for https://ohi-science.nceas.ucsb.edu/chn
study_area:       China
git_owner:        OHI-Science
git_repo:         chn
git_slug:         OHI-Science/chn
git_url:          https://github.com/OHI-Science/chn
app_url:          http://ohi-science.nceas.ucsb.edu/chn
default_branch:   published
default_scenario: subcountry2014
debug:            False
last_updated:     2015-03-24
ohicore_app:
  git_owner: ohi-science
  git_repo: ohicore
  git_branch: dev
  git_commit: 3d428b266e40346da767c1026938279977302a3a

tabs_hide:        
- Calculate
- Report

