---
output: html_document
---

## Food Provision: Fisheries
Amount of sustainable wild-caught seafood compared to the reference multi-species max sustainable yield [$mMSY_{R}$]

$$
x_{FIS} =  (1 - \frac{\delta{C_{t}}}{mMSY_{R}})
$$  

$$
\delta{C_{t}} = 
   \begin{cases}
    0                      &\quad \text{if }\ |{mMSY_{r}}-{C_{t}}| < {{0.05}*{mMSY_{r}}}\\
    |{mMSY_{r}}-{C_{t}}|   &\quad \text{if }\ |{mMSY_{r}}-{C_{t}}| < {mMSY_{r}}\\
    {mMSY_{r}}                 &\quad \text{otherwise }
   \end{cases}
$$

\textit{How to calculate mMSY:}
How to calculate mMSY:

$$
B_{t+1} = B_{t} + rB_{t}(1 - \frac{B_{t}}{k}) - C_{t}
$$

$$
C_{t} = qB_{t}f_{t}
$$

$$
B_{t} = U_{t}/q
$$

$$
U_{t} = \frac{C_{t}}{f_{t}}
$$

$$
\frac{U_{t+1}}{q} = \frac{U_{t}}{q} + \frac{rU_{t}}{q[1-\frac{U_{t}}{Kq}]} - U_{t}{f_t}
$$

$$
\frac{U_{t+1}}{U_t} = r - \frac{rU_{t}}{Kq} - qf_{t}
$$

This equation can be converted to a linear regrssion model:
$$
Y = b_{o} + b_{1}x_{1} + b_{2}x_{2}
$$
$r$,$q$,$K$ values can be obtained by solving the linear regression, and thus $mMSY$

$$
mMSY = rK/4
$$
$$
mMSY_{r} = 0.75 * mMSY
$$



- $mMSY_{r}$ = Reference Maxium sustainable yield ($0.75*mMMSY$)

- $C$ = total catch at time [$t$]

- $\delta{C_{t}}$ = absolute difference between total landed biomass at time [$t$] and mMSY_{r}

- $B$ = total biomass at time [$t$]

- $r$ = natural growth rate

- $K$ = carry capacity

- $C$ = total landed biomass at time [$t$]

- $q$ = catch coefficient

- $U$ = fishing efforts at time [$t$]

## Food Provision: Mariculture
Amount of sustainable farm-raised seafood compared to max sustainable

$$
x_{MAR} =  \frac{Y_{c}}{Y_{r}}
$$

$$
Y_{c} = \frac{\sum_{1}^{k} Y_{k} * S_{M,k}}{P_{c}}
$$

- $Y$ = current sustainably harvested total yield, current [$c$] or reference [$r$] 

- $S_{M,k}$ = Sustainability score for each species $k$

- $P_{c}$ = Coastal population within 100km

- $Y_{r} = max(Y_{c})$


## Artisanal Fishing Opportunity 
the opportunity to fish artisanally, independent of how many fish are caught

$$
x_{AO} =\frac{\frac{AP_{c}}{AP_{r}} + \frac{AF_{c}}{AF_{r}} + AE_{i} }{3}
$$

$$
AE_{i} = \frac{G_{r}}{I_{r}} - \frac{G_{c}}{I_{c}}
$$

- $AP$ = number of ports, current [$c$] or reference [$r$]

- $AF$ = number of fishermen, current [$c$] or reference [$r$]

- $AE$ = economic factor to affect artisinal fishing 

- $G$ = diesel price, current [$c$] or reference [$r$] 

- $I$ = average yearly disposable income, current [$c$] or reference [$r$]


## Natural Products
Level of protection of the coast from inundation and erosion compared to the local natural potential

$$
x_{NP} = \frac{\sum_{p=1}^{N} w_p * x_p}{N}  
$$

$$
x_p = H_p * S_p
$$

$$
S_p = 1 - (\frac{E + R}{N})  
$$

- $w_p$ = proportional peak US dollar value of product $p$  

- $x_p$ = sustainable-harvest score for product $p$  

- $H_p$ = harvest yield for product $p$  

- $S_p$ = sustainability of product $p$ 

- $E$ = exposure term 

- $R$ = risk term

- $N$ = number of natural products

￼products:seasalt, marine chemicals, biomedicine


## Carbon Storage
Extent and condition of coastal habitats that store and sequester atmospheric carbon 

$$
x_{CS} =  \sum_{1}^{k} ( c_k * \frac{C_{c}}{C_{r}} * \frac{A_{k}}{A_{T}} )
$$

- $C$ = condition of habitat $k$, current [$c$] or reference[$r$]

- $A$ = area of habitat $k$, current [$c$] or total area covered by all habitats assessed [T]

- ${c_k}$ = relative contribution to carbon storage by each habitat

habitats: seagrass beds, salt marshes, mangroves


## Coastal Protection
Protection from inundation or erosion compared to the local natural potential

$$
x_{CP} =  \sum_{i=1}^{k} ( \frac{C_c}{C_r} * \frac {w_k}{w_max} * \frac{A_k}{A_T} )
$$


- $C$ = condition of habitat $k$, current [$c$] and reference [$r$]

- $w$ = weighted capacity of habitat $k$ to protect the coast

- $A$ = coverage area of habitat $k$ 

habitats: salt marshes, seagrass beds, mangroves, coral reefs, sea ice


## Tourism & Recreation
Tourism & recreation value, independent of monetary exchange

$$
x_{TR} = \log (\frac{A_t}{V_t} * {S_t} + {1})
$$

- $A$ = number of tourists in year $t$ 

- $V$ = area within jurisdiction 

- $S$ = sustainability coefficient, set as 0.787 (China TTCI, 2009)


## Livelihoods & Economies: Livelihoods
Number of jobs and job quality from marine-associated sectors

$$
x_{LIV} = \frac{\frac{\sum_{i=1}^{k} j_{c,k}}{\sum_{i=1}^{k} j_{r,k}} + \frac{g_{c}} {g_{r}}}{2}
$$

$$
j_{c(c, k)} = N_{k} * \frac{x}{\sum{x}}
$$

- $j$ = number of jobs within sector $k$ at current [$c$] time or reference [$r$] level

- $g$ = sum of average urban and rural family income in current time [$c$] or reference [$r$] level

- sectors ($k$): tourism, commercial fishing, marine mammal watching, aquarium fishing, wave & tidal energy, mariculture, transportation & shipping, ports & harbors, ship & boatbuilding

- $N$ = total number of employment in each sector [$k$] across all regions

- $x$ = total number of employments across all sectors in each region


## Livelihoods & Economies: Economies
Revenue from marine associated sectors

$$
x_{ECO} = \frac{e_{c}}{e_{r}} 
$$

- $e$ = total revenue generated from all sectors at current time [$c$] or reference [$r$] level

## Sense of Place: Iconic Species
Aesthetic connections to and cultural identity with a given region measured through the status of iconic species

$$
x_{ICO} = \frac{\sum_{i=1}^{N} S_{i} * w_{i}}{\sum_{i=1}^{N} S_{i}} 
$$

- $S$ = number of assessed species in each threat category $i$ 

- $w$ = status weight assigned per threat category $i$ 

- $N$ = 6 threat categories 

iconic species list: WWF Priority Species

threat categories: IUCN


## Sense of Place: Lasting Special Places
Aesthetic connections to and cultural identity with a given region measured through the status of meaningful locations


$$
x_{LSP} = \frac{\%{CMPA}}{\%CMPA_{Ref}} 
$$

- ${\%CMPA}$ = percent protected marine coastal area of the coastal region within jurisdiction

- ${\%CMPA_{Ref}}$ = %5, reference percent protected marine costal area of the coastal region within jurisdiction


## Clean Waters
The degree to which coastal waters are free of contaminants

$$
x_{CW} = \sqrt[4]{\prod{a_{i}}}
$$

- $a$  = water pollution input

- $i$ = type of pollution, including phosphate, nitrogen, chemical oxygen demand, and oil pollution


## Biodiversity: Habitats
Existence values people hold for biodiversity measured through the status of key habitats

$$
x_{HAB} = \frac{ \sum_{i=1}^{k} \frac{C_{c,k}}{C_{r,k}}}{N}
$$

- $C$ = condition of habitat k, current [$c$] or reference[$r$]

- $N$ = total number of habitat assessed in the region

Habitats include seagrass beds, salt marshes, mangroves


## Biodiversity: Species
Existence values people hold for biodiversity measured through the status of native species

$$
x_{SPP} = 1 - \frac{\sum_{i=1}^{N} w_{i}}{N}
$$


- $N$ = number of assessed species in the province

- $w_{i}$ = status weight assigned per threat 

assessed species list and maps: IUCN
